### ISSUE TITLE
Aftellen geluid afspelen op laatste 10 seconden

### ISSUE THREAD

**Issue by mixxamm** [AP-TI/ReactNieuwjaarAfteller#1]
Ik wil aftellen.wav laten afspelen op de laatste 10 seconden, heb al vanalles geprobeerd maar ik krijg het maar niet in orde. Het bestand aftellen.wav staat in het mapje 'public'.

**Comment by MrDanaT** [comment]
Veranderd naar een class component en deze in de render() method gestoken. Bij elke nieuw render, zal het dusdanig checken of het <= 10000 seconden over zijn of niet.
